window.EXPERIMENT_STIMULI = [
  { id: 1, originalId: 36, word: "casket", ipa: "/ˈkæskɪt/", ja: "棺", phonemes: 7, syllables: 2, originalList: 2, list: 1, image: "images/casket.jpg" },
  { id: 2, originalId: 50, word: "catapult", ipa: "/ˈkætəˌpʌlt/", ja: "投石機", phonemes: 8, syllables: 3, originalList: 2, list: 1, image: "images/catapult.jpg" },
  { id: 3, originalId: 49, word: "chisel", ipa: "/ˈtʃɪzəl/", ja: "彫刻刀", phonemes: 6, syllables: 2, originalList: 2, list: 1, image: "images/chisel.jpg" },
  { id: 4, originalId: 29, word: "cocoon", ipa: "/kəˈkun/", ja: "繭、かいこ", phonemes: 5, syllables: 2, originalList: 2, list: 1, image: "images/cocoon.jpg" },
  { id: 5, originalId: 12, word: "faucet", ipa: "/ˈfɔsət/", ja: "蛇口", phonemes: 5, syllables: 2, originalList: 1, list: 1, image: "images/faucet.jpg" },
  { id: 6, originalId: 18, word: "ladle", ipa: "/ˈleɪdəl/", ja: "おたま", phonemes: 5, syllables: 2, originalList: 1, list: 1, image: "images/ladle.jpg" },
  { id: 7, originalId: 6, word: "persimmon", ipa: "/pərˈsɪmən/", ja: "柿", phonemes: 7, syllables: 3, originalList: 1, list: 1, image: "images/persimmon.jpg" },
  { id: 8, originalId: 20, word: "protractor", ipa: "/prəˈtræktər/", ja: "分度器", phonemes: 8, syllables: 3, originalList: 1, list: 1, image: "images/protractor.jpg" },
  { id: 9, originalId: 13, word: "tadpole", ipa: "/ˈtædˌpoʊl/", ja: "オタマジャクシ", phonemes: 7, syllables: 2, originalList: 1, list: 1, image: "images/tadpole.jpg" },
  { id: 10, originalId: 26, word: "toboggan", ipa: "/təˈbɑːɡən/", ja: "そり", phonemes: 7, syllables: 3, originalList: 2, list: 1, image: "images/toboggan.jpg" },
  { id: 11, originalId: 14, word: "tweezers", ipa: "/ˈtwizərz/", ja: "ピンセット", phonemes: 7, syllables: 2, originalList: 1, list: 1, image: "images/tweezers.jpg" },
  { id: 12, originalId: 30, word: "wardrobe", ipa: "/ˈwɔrdˌroʊb/", ja: "タンス", phonemes: 7, syllables: 2, originalList: 2, list: 1, image: "images/wardrobe.jpg" },
  { id: 13, originalId: 4, word: "acorn", ipa: "/ˈeɪkɔrn/", ja: "どんぐり", phonemes: 5, syllables: 2, originalList: 1, list: 2, image: "images/acorn.jpg" },
  { id: 14, originalId: 47, word: "capelin", ipa: "/ˈkæpəlɪn/", ja: "ししゃも", phonemes: 7, syllables: 3, originalList: 2, list: 2, image: "images/capelin.jpg" },
  { id: 15, originalId: 1, word: "icicle", ipa: "/ˈaɪsɪkəl/", ja: "つらら", phonemes: 7, syllables: 3, originalList: 1, list: 2, image: "images/icicle.jpg" },
  { id: 16, originalId: 44, word: "loquat", ipa: "/ˈloʊkwɑt/", ja: "ビワ", phonemes: 6, syllables: 2, originalList: 2, list: 2, image: "images/loquat.jpg" },
  { id: 17, originalId: 7, word: "mantis", ipa: "/ˈmæntɪs/", ja: "カマキリ", phonemes: 6, syllables: 2, originalList: 1, list: 2, image: "images/mantis.jpg" },
  { id: 18, originalId: 32, word: "parakeet", ipa: "/ˈpærəˌkit/", ja: "インコ", phonemes: 8, syllables: 3, originalList: 2, list: 2, image: "images/parakeet.jpg" },
  { id: 19, originalId: 27, word: "porcupine", ipa: "/ˈpɔrkjəˌpaɪn/", ja: "ヤマアラシ", phonemes: 8, syllables: 3, originalList: 2, list: 2, image: "images/porcupine.jpg" },
  { id: 20, originalId: 15, word: "rickshaw", ipa: "/ˈrɪkˌʃɔ/", ja: "人力車", phonemes: 5, syllables: 2, originalList: 1, list: 2, image: "images/rickshaw.jpg" },
  { id: 21, originalId: 33, word: "scallop", ipa: "/ˈskɑləp/", ja: "ホタテ", phonemes: 7, syllables: 2, originalList: 2, list: 2, image: "images/scallop.jpg" },
  { id: 22, originalId: 38, word: "scalpel", ipa: "/ˈskælpəl/", ja: "メス", phonemes: 7, syllables: 2, originalList: 2, list: 2, image: "images/scalpel.jpg" },
  { id: 23, originalId: 9, word: "syringe", ipa: "/səˈrɪndʒ/", ja: "注射器", phonemes: 6, syllables: 2, originalList: 1, list: 2, image: "images/syringe.jpg" },
  { id: 24, originalId: 22, word: "treadmill", ipa: "/ˈtrɛdˌmɪl/", ja: "ランニングマシン", phonemes: 7, syllables: 2, originalList: 1, list: 2, image: "images/treadmill.jpg" },
];
